### ISSUE TITLE
Old version of mfp works with dldh. the new mfp doesn’t work with some channels

### ISSUE THREAD

**Issue by ciccioxm3** [mhdzumair/mediaflow-proxy#101]
Hi,

the old version of MFP is working good with DLDH, with embed/stream link,

the new one is not working with stream/stream and embed/stream,

https://192.168.1.23:8888/extractor/video?host=DLHD&d=https%3A%2F%2Fdaddylive.dad%2Fembed%2Fstream-881.php&redirect_stream=true&api_password=psw

this is not working with new version, also with stream/stream, same result

[https://192.168.23:8888/extractor/video?host=DLHD&d=https%3A%2F%2Fdaddylive.dad%2Fembed%2Fstream-881.php&redirect_stream=true&api_password=mfp](https://192.168.0.23:8888/extractor/video?host=DLHD&d=https%3A%2F%2Fdaddylive.dad%2Fembed%2Fstream-881.php&redirect_stream=true&api_password=mfp)

this is working with old version of mfp

{"detail":"Extraction failed: Could not extract player URL from playnow response"}

**Comment by absinth19** [comment]
Same problem here too, .php DDHL stream or embed links don't start after the latest updates, they only start on old MFP versions.
Thanks in advance for the fix!

**Comment by ciccioxm3** [comment]
The old version is the one in docker hub, the docker image is working, the actual version of the code is not working, let me check how can I see the version number

**Comment by absinth19** [comment]
https://github.com/mhdzumair/mediaflow-proxy/tree/d0baf111bc16e9f885e116d24c323100c38d9913 last version working fine for DDHL pph

**Comment by absinth19** [comment]
That link point to d0baf11 commit.

**Comment by grahams** [comment]
It seems more complicated...  ESPN (stream-44) works but NESN (stream-762) does not, for example.  I'm presently trying to debug and see if I can track down what is going on

**Comment by grahams** [comment]
@ciccioxm3 Not entirely true.  The changes in the current version were intended to fix some streams which were broken on 2.1.4 (for example, stream-31) due to double iframes.  I can confirm, though, that stream-762, does work on 2.1.4, so I think the changes need to be revisited.

**Comment by ciccioxm3** [comment]
> [@ciccioxm3](https://github.com/ciccioxm3) Not entirely true. The changes in the current version were intended to fix some streams which were broken on 2.1.4 (for example, stream-31) due to double iframes. I can confirm, though, that stream-762, does work on 2.1.4, so I think the changes need to be revisited.

i've made a change on dlhd.py, now 31, 762 and 881,877 are working, i will push the code soon, let me test it a little bit

**Comment by ciccioxm3** [comment]
> [@ciccioxm3](https://github.com/ciccioxm3) Not entirely true. The changes in the current version were intended to fix some streams which were broken on 2.1.4 (for example, stream-31) due to double iframes. I can confirm, though, that stream-762, does work on 2.1.4, so I think the changes need to be revisited.

Done, if you want to try you can find the code in pullrequest or on my repo, mfp

**Comment by grahams** [comment]
I patched in your version (using a docker volume mapping) and can confirm that with your version of `dlhd.py` I am able to stream all of the channels I've tried, including those four.   They work via `mpv` and in safari for me.

Strangely, things are still broken for me in channels-dvr and I'm not sure why, but I don't think that is related to this issue.
